### PR TITLE
Added new MXML (MX and Spark) snippets

### PR DESCRIPTION
**Pull request by neminovno**

### CODE REVIEW

**Comment by joshtynjala** [comment]
Thanks for the contribution! I'm thinking that maybe we should make this into a separate extension. Not everyone using MXML is necessarily using Flex, since there is also Royale and Feathers. It would be good if these snippets were only presented to developers who actually want them.

**Comment by neminovno** [comment]
Oh, I should have asked that in this issue https://github.com/BowlerHatLLC/vscode-nextgenas/issues/200
So there is no way in the extension to differentiate which snippets are provided based on if it is Flex, Royale or Feathers in use? If so, then it would be better to pack them in separate extension, and mention that in Wiki.

**Comment by joshtynjala** [comment]
No, I don't think it's possible to enable only a subset of snippets. You always get the full list for any file in the language that they're designed for.

**Comment by neminovno** [comment]
Done, as [new extension](https://github.com/neminovno/vscode-flex-snippets).

image

**Comment by joshtynjala** [comment]
Nice! I'll be sure to share it on social media next week.

**Comment by piotrzarzycki21** [comment]
Cool! It doesn't look too complicated. Maybe I will create such repository also for Royale. I will add it to my To Do list!

**Pull request closed without merging**
